version: "3.4"
services:
  web:
    build: .
    depends_on:
      - pg
    ports:
      - "5000:5000"
      - "80:5000"
    environment:
      - FLASK_CONFIG=production
      - FLASK_APP=app/main.py
      - FLASK_DEBUG
      - GOOGLE_APPLICATION_CREDENTIALS
      - JSON_KEYFILE
    volumes:
      - ./app:/mis2018/app
      - ./migrations:/mis2018/migrations
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=genius01
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5443:5432"

