version: "3.4"
services:
  web:
    build: .
    depends_on:
      - pg
    ports:
      - "5000:5000"
      - "80:5000"
    env_file:
      - web_variables.env
    environment:
      - FLASK_CONFIG
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - SCOPUS_API_KEY
    volumes:
      - ./app:/mis2018/app
      - ./warehouse:/mis2018/warehouse
      - ./migrations:/mis2018/migrations
  pg:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5443:5432"

