version: "3.4"
services:
  web:
    build: .
    depends_on:
      - pg
    ports:
      - "5000:5000"
    environment:
      - FLASK_CONFIG=production
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app"

  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=genius01
    volumes:
      - mumtmis-data:/var/lib/postgresql/data
    ports:
      - "5443:5432"

volumes:
  mumtmis-data:
    external: true

networks:
  default:
    external:
      name: mumtmis