version: "3.4"
services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build: .
    depends_on:
      - pg
    ports:
      - 5000
    env_file:
      - web_variables.env
    environment:
      - FLASK_CONFIG
      - FLASK_DEBUG
      - POSTGRES_PASSWORD
      - DEV_DATABASE
      - DATABASE
      - SECRET_KEY
      - SCOPUS_API_KEY
    volumes:
      - ./app:/mis2018/app
      - ./warehouse:/mis2018/warehouse
      - ./migrations:/mis2018/migrations
  pg:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - misdata:/var/lib/postgresql/data
    ports:
      - "5443:5432"

volumes:
  misdata:
